version: '3.8'

services:
  # Main API service
  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - ENABLE_AUTH_BYPASS=${ENABLE_AUTH_BYPASS:-false}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - supabase-db
      - supabase-kong
    networks:
      - meat-api-network

  # Supabase Database
  supabase-db:
    image: supabase/postgres:15.1.0.117
    ports:
      - "${DB_PORT:-54322}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - supabase-db-data:/var/lib/postgresql/data
    networks:
      - meat-api-network

  # Supabase Kong (API Gateway)
  supabase-kong:
    image: kong:2.8.1
    ports:
      - "${KONG_PORT:-54321}:8000"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/var/lib/kong/kong.yml
      - KONG_DNS_ORDER=LAST,A,CNAME
      - KONG_PLUGINS=request-transformer,cors,key-auth,acl,basic-auth
    volumes:
      - ./supabase/kong.yml:/var/lib/kong/kong.yml:ro
    depends_on:
      - supabase-db
    networks:
      - meat-api-network

volumes:
  supabase-db-data:

networks:
  meat-api-network:
    driver: bridge 